//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TZOmPavMalPech.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Readed = new HashSet<Readed>();
        }
    
        public int Id_Books { get; set; }
        public string Name { get; set; }
        public string Avtor { get; set; }
        public System.DateTime DateBook { get; set; }
        public Nullable<int> Genre_Id { get; set; }
        public Nullable<int> Publisher_Id { get; set; }
        public string Discription { get; set; }
        public string Image { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Readed> Readed { get; set; }
    }
}
