//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TZOmPavMalPech.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Readed
    {
        public int Id_Readed { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Books_Id { get; set; }
        public Nullable<int> is_read { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual User User { get; set; }
    }
}
